---

- name: template in nvidia_persistence.service systemd script
  template:
    src: nvidia_persistence.service.j2
    dest: /etc/systemd/system/nvidia_persistence.service
    mode: 0644
  notify:
    - reload systemd unit files
    - Restart nvidia_persistence service
  when: ansible_service_mgr == "systemd"

- name: enable the nvidia_persistence systemd service
  service:
    name: nvidia_persistence
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: check if cuda_gpu_name0 ( /dev/nvidia0 ) exists
  stat:
    path: "{{ cuda_gpu_name0 }}"
  register: reg_cuda_gpu_name0
  always_run: True

- debug:
    var: reg_cuda_gpu_name0
    verbosity: 1

# vim:ft=ansible:
